version: '3.9'

services:
  mysqldb:
    image: mysql:8.0.30
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=cotacao_crypto
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - net

  cotacao-crypto:
    depends_on:
      - mysqldb
        # condition: service_healthy
    command: ["./wait-for-it.sh", mysqldb:3306, "--", "node", "./build/src/server.js"]
    image: alexdamiao86/cotacao-crypto-api:1.1.0
    # Desasteriscar linhas abaixo para realizar build local da imagem
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: cotacao-crypto
    ports:
    - 5555:5555
    environment:
      - MYSQLDB_HOST=mysqldb
      - MYSQLDB_USER=root
      - MYSQLDB_ROOT_PASSWORD=123456
      - MYSQLDB_DATABASE=cotacao_crypto
      - MYSQLDB_DOCKER_PORT=3306
    stdin_open: true
    tty: true
    deploy:
      replicas: 3
      restart_policy:
        condition: on_failure
        max_attempts: 3
    networks:
      - net

volumes:
  db:

networks:
  net:
    external: true


